"""Schéma initial versionné de PerspectiV."""

from alembic import op
import sqlalchemy as sa


revision = "20260929_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("username", sa.String(64), nullable=False), sa.Column("full_name", sa.String(160), nullable=False), sa.Column("email", sa.String(160)), sa.Column("role", sa.String(32), nullable=False), sa.Column("password_hash", sa.String(220), nullable=False), sa.Column("hourly_rate", sa.Numeric(12, 2), nullable=False), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("oidc_subject", sa.String(255)), sa.UniqueConstraint("username"), sa.UniqueConstraint("oidc_subject"))
    op.create_index("ix_users_username", "users", ["username"])
    op.create_index("ix_users_oidc_subject", "users", ["oidc_subject"])
    op.create_table("user_grid_preferences", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("grid_key", sa.String(120), nullable=False), sa.Column("visible_columns", sa.Text(), nullable=False), sa.UniqueConstraint("user_id", "grid_key", name="uq_user_grid_preference"))
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(24), nullable=False), sa.Column("name", sa.String(180), nullable=False), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("category", sa.String(80), nullable=False), sa.Column("priority", sa.String(32), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("start_date", sa.Date()), sa.Column("end_date", sa.Date()), sa.Column("budget_amount", sa.Numeric(14, 2), nullable=False), sa.Column("budget_hours", sa.Numeric(10, 2), nullable=False), sa.Column("description", sa.Text()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("code"))
    op.create_index("ix_projects_code", "projects", ["code"])
    op.create_index("ix_projects_name", "projects", ["name"])
    op.create_table("budgets", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("reference", sa.String(40), nullable=False), sa.Column("label", sa.String(180), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("planned_amount", sa.Numeric(14, 2), nullable=False), sa.Column("committed_amount", sa.Numeric(14, 2), nullable=False), sa.Column("actual_amount", sa.Numeric(14, 2), nullable=False), sa.UniqueConstraint("reference"), sa.UniqueConstraint("project_id", "reference", name="uq_project_budget_reference"))
    op.create_table("budget_lines", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("budget_id", sa.Integer(), sa.ForeignKey("budgets.id")), sa.Column("category", sa.String(80), nullable=False), sa.Column("label", sa.String(180), nullable=False), sa.Column("planned_amount", sa.Numeric(14, 2), nullable=False), sa.Column("committed_amount", sa.Numeric(14, 2), nullable=False), sa.Column("actual_amount", sa.Numeric(14, 2), nullable=False))
    op.create_table("tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("budget_id", sa.Integer(), sa.ForeignKey("budgets.id")), sa.Column("budget_line_id", sa.Integer(), sa.ForeignKey("budget_lines.id")), sa.Column("reference", sa.String(40), nullable=False), sa.Column("title", sa.String(220), nullable=False), sa.Column("level", sa.Integer(), nullable=False), sa.Column("parent_id", sa.Integer(), sa.ForeignKey("tasks.id")), sa.Column("status", sa.String(32), nullable=False), sa.Column("priority", sa.String(32), nullable=False), sa.Column("starcost", sa.Boolean(), nullable=False), sa.Column("start_date", sa.Date()), sa.Column("due_date", sa.Date()), sa.Column("planned_hours", sa.Numeric(10, 2), nullable=False), sa.Column("planned_cost", sa.Numeric(14, 2), nullable=False), sa.Column("actual_hours", sa.Numeric(10, 2), nullable=False), sa.Column("actual_labor_cost", sa.Numeric(14, 2), nullable=False), sa.Column("actual_expense_amount", sa.Numeric(14, 2), nullable=False), sa.Column("actual_total_cost", sa.Numeric(14, 2), nullable=False), sa.Column("actual_end_date", sa.Date()), sa.Column("progress", sa.Integer(), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False), sa.Column("description", sa.Text()), sa.UniqueConstraint("reference"))
    op.create_index("ix_tasks_project_id", "tasks", ["project_id"])
    op.create_table("task_assignments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("task_id", sa.Integer(), sa.ForeignKey("tasks.id"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("role", sa.String(100)), sa.Column("planned_hours", sa.Numeric(10, 2), nullable=False), sa.Column("cost_rate", sa.Numeric(12, 2), nullable=False), sa.UniqueConstraint("task_id", "user_id", name="uq_task_user"))
    op.create_table("task_dependencies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("predecessor_id", sa.Integer(), sa.ForeignKey("tasks.id"), nullable=False), sa.Column("successor_id", sa.Integer(), sa.ForeignKey("tasks.id"), nullable=False), sa.Column("link_type", sa.String(32), nullable=False), sa.Column("lag_days", sa.Integer(), nullable=False), sa.UniqueConstraint("predecessor_id", "successor_id", name="uq_dependency_pair"))
    op.create_table("time_entries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("task_id", sa.Integer(), sa.ForeignKey("tasks.id"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("entry_date", sa.Date(), nullable=False), sa.Column("hours", sa.Numeric(8, 2), nullable=False), sa.Column("cost_rate", sa.Numeric(12, 2), nullable=False), sa.Column("cost_amount", sa.Numeric(14, 2), nullable=False), sa.Column("note", sa.Text()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("planned_time_entries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("task_id", sa.Integer(), sa.ForeignKey("tasks.id"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("entry_date", sa.Date(), nullable=False), sa.Column("hours", sa.Numeric(8, 2), nullable=False), sa.Column("note", sa.Text()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("source", sa.String(24), nullable=False), sa.Column("action", sa.String(80), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(80)), sa.Column("before_json", sa.Text()), sa.Column("after_json", sa.Text()), sa.Column("result", sa.String(24), nullable=False), sa.Column("request_id", sa.String(64)), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("idempotency_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("operation", sa.String(80), nullable=False), sa.Column("idempotency_key", sa.String(160), nullable=False), sa.Column("response_json", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("user_id", "operation", "idempotency_key", name="uq_idempotency"))
    op.create_table("delete_confirmations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("token_hash", sa.String(64), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.Integer(), nullable=False), sa.Column("expires_at", sa.DateTime(), nullable=False), sa.Column("used_at", sa.DateTime()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("token_hash"))


def downgrade() -> None:
    for table in ["delete_confirmations", "idempotency_records", "audit_logs", "planned_time_entries", "time_entries", "task_dependencies", "task_assignments", "tasks", "budget_lines", "budgets", "projects", "user_grid_preferences", "users"]:
        op.drop_table(table)
